schema-version: v2
kind: plugin
metadata:
  name: go-openapi
  display-name: go-openapi
  description: Describe your plugin explaining its purpose
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: https://github.com/Aspoos/stk-go-openapi.git
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  stk-projects-only: false
  inputs:
    - label: Utilizar openapi ?
      name: use_openapi
      type: bool
      default: false
      required: true

  computed-inputs:
      inner_project_name: "{{default_project_name or 'default_value'}}"

  hooks:
  - type: run
    trigger: before-render
    working-dir: "."
    commands:
      - mkdir api
      - touch api/openapi.yaml
    condition:
      variable: use_openapi
      operator: "=="
      value: true

  - type: edit
    trigger: after-render
    path: "api/openapi.yaml"
    changes:
    - insert:
        line: 0
        snippet: snippet/content_openapi.txt
        when:
          not-exists-snippet: snippet/content_openapi.txt
    condition:
      variable: use_openapi
      operator: "=="
      value: true        


